### ISSUE TITLE
上传成功无返回URL、同时文件夹已存在也会出错

### ISSUE THREAD

**Issue by hedeqiang** [JellyBool/flysystem-upyun#11]
```
$disk = Storage::disk('upyun');
return $disk->write($folder_name, $file);
```
以上代码上传成功但是 filename 为 null

![image](https://user-images.githubusercontent.com/31909061/57528536-2f104f80-7365-11e9-885e-0a6d7cc7a89c.png)

同时如果又拍云已存在目录，也会报错

![image](https://user-images.githubusercontent.com/31909061/57528595-55ce8600-7365-11e9-8715-d80bcc829bb2.png)

**Comment by JellyBool** [comment]
你的文件是多大啊？感觉后面的这个错误是因为你原来的文件没上传完整，后来又冲突了。
