### ISSUE TITLE
配置以后 发现没有找到API方法

### ISSUE THREAD

**Issue by cuncle** [JellyBool/flysystem-upyun#2]
使用API方法：$flysystem->write  出现错误：Fatal error:  Uncaught Error: Call to a member function delete() on null
 报错类型不对

**Comment by JellyBool** [comment]
`delete() on null` 这个应该是你某个地方的代码逻辑错了

**Comment by cuncle** [comment]
你好，你这边有没有写好的examples可以参考一下

**Comment by JellyBool** [comment]
你看一下我录的这个视频吧。视频有讲到

https://www.laravist.com/series/awesome-laravel-packages/episodes/8
