### ISSUE TITLE
上传非图片文件返回结果异常？

### ISSUE THREAD

**Issue by 7thpark** [JellyBool/flysystem-upyun#3]
例如：
https://github.com/JellyBool/flysystem-upyun/blob/master/src/UpyunAdapter.php#L71
调用的`write`方法根据 upyun 的说明返回的结果：
```
  * @return array|bool 若文件是图片则返回图片基本信息，如：`array('x-upyun-width' => 123, 'x-upyun-height' => 50, 'x-upyun-frames'
  * => 1, 'x-upyun-file-type' => 'JPEG')`，否则返回空数组。当使用异步预处理功能时，返回结果为布尔值，成功为 `true`。
```
上传非图片时返回的是空数组，`Storage` 的 `put` 方法会返回 false，但实际上传成功了。

**Comment by JellyBool** [comment]
欢迎 PR @7thpark 

> 不好意思，最近出去泰国玩，才回来
